### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.logic.models.batch_configuration.BatchConfiguration
  fullName: azure.mgmt.logic.models.batch_configuration
  langs:
  - python
  module: azure.mgmt.logic.models.batch_configuration
  name: batch_configuration
  source:
    id: batch_configuration
    path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.logic.models.batch_configuration
references:
- fullName: azure.mgmt.logic.models.batch_configuration.BatchConfiguration
  isExternal: false
  name: BatchConfiguration
  parent: azure.mgmt.logic.models.batch_configuration
  uid: azure.mgmt.logic.models.batch_configuration.BatchConfiguration
