### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.logic.models.as2_mdn_settings_py3.AS2MdnSettings
  fullName: azure.mgmt.logic.models.as2_mdn_settings_py3
  langs:
  - python
  module: azure.mgmt.logic.models.as2_mdn_settings_py3
  name: as2_mdn_settings_py3
  source:
    id: as2_mdn_settings_py3
    path: azure-mgmt-logic\azure\mgmt\logic\models\as2_mdn_settings_py3.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\models\as2_mdn_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.logic.models.as2_mdn_settings_py3
references:
- fullName: azure.mgmt.logic.models.as2_mdn_settings_py3.AS2MdnSettings
  isExternal: false
  name: AS2MdnSettings
  parent: azure.mgmt.logic.models.as2_mdn_settings_py3
  uid: azure.mgmt.logic.models.as2_mdn_settings_py3.AS2MdnSettings
