### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection.DiagnosticSettingsCategoryResourceCollection
  fullName: azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection
  langs:
  - python
  module: azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection
  name: diagnostic_settings_category_resource_collection
  source:
    id: diagnostic_settings_category_resource_collection
    path: azure-mgmt-monitor\azure\mgmt\monitor\models\diagnostic_settings_category_resource_collection.py
    remote:
      branch: master
      path: azure-mgmt-monitor\azure\mgmt\monitor\models\diagnostic_settings_category_resource_collection.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection
references:
- fullName: azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection.DiagnosticSettingsCategoryResourceCollection
  isExternal: false
  name: DiagnosticSettingsCategoryResourceCollection
  parent: azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection
  uid: azure.mgmt.monitor.models.diagnostic_settings_category_resource_collection.DiagnosticSettingsCategoryResourceCollection
