### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.monitor.models.metric_settings_py3.MetricSettings
  fullName: azure.mgmt.monitor.models.metric_settings_py3
  langs:
  - python
  module: azure.mgmt.monitor.models.metric_settings_py3
  name: metric_settings_py3
  source:
    id: metric_settings_py3
    path: azure-mgmt-monitor\azure\mgmt\monitor\models\metric_settings_py3.py
    remote:
      branch: master
      path: azure-mgmt-monitor\azure\mgmt\monitor\models\metric_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.monitor.models.metric_settings_py3
references:
- fullName: azure.mgmt.monitor.models.metric_settings_py3.MetricSettings
  isExternal: false
  name: MetricSettings
  parent: azure.mgmt.monitor.models.metric_settings_py3
  uid: azure.mgmt.monitor.models.metric_settings_py3.MetricSettings
