### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resource.managedapplications.operations.applications_operations.ApplicationsOperations
  fullName: azure.mgmt.resource.managedapplications.operations.applications_operations
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.operations.applications_operations
  name: applications_operations
  source:
    id: applications_operations
    path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\operations\applications_operations.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\operations\applications_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.resource.managedapplications.operations.applications_operations
references:
- fullName: azure.mgmt.resource.managedapplications.operations.applications_operations.ApplicationsOperations
  isExternal: false
  name: ApplicationsOperations
  parent: azure.mgmt.resource.managedapplications.operations.applications_operations
  uid: azure.mgmt.resource.managedapplications.operations.applications_operations.ApplicationsOperations
