### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.batch.models.container_configuration.ContainerConfiguration
  fullName: azure.batch.models.container_configuration
  langs:
  - python
  module: azure.batch.models.container_configuration
  name: container_configuration
  source:
    id: container_configuration
    path: azure-batch\azure\batch\models\container_configuration.py
    remote:
      branch: master
      path: azure-batch\azure\batch\models\container_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.batch.models.container_configuration
references:
- fullName: azure.batch.models.container_configuration.ContainerConfiguration
  isExternal: false
  name: ContainerConfiguration
  parent: azure.batch.models.container_configuration
  uid: azure.batch.models.container_configuration.ContainerConfiguration
