### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.tensor_flow_settings_py3.TensorFlowSettings
  fullName: azure.mgmt.batchai.models.tensor_flow_settings_py3
  langs:
  - python
  module: azure.mgmt.batchai.models.tensor_flow_settings_py3
  name: tensor_flow_settings_py3
  source:
    id: tensor_flow_settings_py3
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\tensor_flow_settings_py3.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\tensor_flow_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.tensor_flow_settings_py3
references:
- fullName: azure.mgmt.batchai.models.tensor_flow_settings_py3.TensorFlowSettings
  isExternal: false
  name: TensorFlowSettings
  parent: azure.mgmt.batchai.models.tensor_flow_settings_py3
  uid: azure.mgmt.batchai.models.tensor_flow_settings_py3.TensorFlowSettings
