### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.container_settings.ContainerSettings
  fullName: azure.mgmt.batchai.models.container_settings
  langs:
  - python
  module: azure.mgmt.batchai.models.container_settings
  name: container_settings
  source:
    id: container_settings
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\container_settings.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\container_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.container_settings
references:
- fullName: azure.mgmt.batchai.models.container_settings.ContainerSettings
  isExternal: false
  name: ContainerSettings
  parent: azure.mgmt.batchai.models.container_settings
  uid: azure.mgmt.batchai.models.container_settings.ContainerSettings
