### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.auto_scale_settings.AutoScaleSettings
  fullName: azure.mgmt.batchai.models.auto_scale_settings
  langs:
  - python
  module: azure.mgmt.batchai.models.auto_scale_settings
  name: auto_scale_settings
  source:
    id: auto_scale_settings
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\auto_scale_settings.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\auto_scale_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.auto_scale_settings
references:
- fullName: azure.mgmt.batchai.models.auto_scale_settings.AutoScaleSettings
  isExternal: false
  name: AutoScaleSettings
  parent: azure.mgmt.batchai.models.auto_scale_settings
  uid: azure.mgmt.batchai.models.auto_scale_settings.AutoScaleSettings
