### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.ssh_configuration_py3.SshConfiguration
  fullName: azure.mgmt.batchai.models.ssh_configuration_py3
  langs:
  - python
  module: azure.mgmt.batchai.models.ssh_configuration_py3
  name: ssh_configuration_py3
  source:
    id: ssh_configuration_py3
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\ssh_configuration_py3.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\ssh_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.ssh_configuration_py3
references:
- fullName: azure.mgmt.batchai.models.ssh_configuration_py3.SshConfiguration
  isExternal: false
  name: SshConfiguration
  parent: azure.mgmt.batchai.models.ssh_configuration_py3
  uid: azure.mgmt.batchai.models.ssh_configuration_py3.SshConfiguration
