### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.caffe2_settings_py3.Caffe2Settings
  fullName: azure.mgmt.batchai.models.caffe2_settings_py3
  langs:
  - python
  module: azure.mgmt.batchai.models.caffe2_settings_py3
  name: caffe2_settings_py3
  source:
    id: caffe2_settings_py3
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\caffe2_settings_py3.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\caffe2_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.caffe2_settings_py3
references:
- fullName: azure.mgmt.batchai.models.caffe2_settings_py3.Caffe2Settings
  isExternal: false
  name: Caffe2Settings
  parent: azure.mgmt.batchai.models.caffe2_settings_py3
  uid: azure.mgmt.batchai.models.caffe2_settings_py3.Caffe2Settings
