### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batch.models.environment_setting.EnvironmentSetting
  fullName: azure.mgmt.batch.models.environment_setting
  langs:
  - python
  module: azure.mgmt.batch.models.environment_setting
  name: environment_setting
  source:
    id: environment_setting
    path: azure-mgmt-batch\azure\mgmt\batch\models\environment_setting.py
    remote:
      branch: master
      path: azure-mgmt-batch\azure\mgmt\batch\models\environment_setting.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batch.models.environment_setting
references:
- fullName: azure.mgmt.batch.models.environment_setting.EnvironmentSetting
  isExternal: false
  name: EnvironmentSetting
  parent: azure.mgmt.batch.models.environment_setting
  uid: azure.mgmt.batch.models.environment_setting.EnvironmentSetting
