### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batch.models.fixed_scale_settings.FixedScaleSettings
  fullName: azure.mgmt.batch.models.fixed_scale_settings
  langs:
  - python
  module: azure.mgmt.batch.models.fixed_scale_settings
  name: fixed_scale_settings
  source:
    id: fixed_scale_settings
    path: azure-mgmt-batch\azure\mgmt\batch\models\fixed_scale_settings.py
    remote:
      branch: master
      path: azure-mgmt-batch\azure\mgmt\batch\models\fixed_scale_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batch.models.fixed_scale_settings
references:
- fullName: azure.mgmt.batch.models.fixed_scale_settings.FixedScaleSettings
  isExternal: false
  name: FixedScaleSettings
  parent: azure.mgmt.batch.models.fixed_scale_settings
  uid: azure.mgmt.batch.models.fixed_scale_settings.FixedScaleSettings
