### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batch.models.windows_configuration.WindowsConfiguration
  fullName: azure.mgmt.batch.models.windows_configuration
  langs:
  - python
  module: azure.mgmt.batch.models.windows_configuration
  name: windows_configuration
  source:
    id: windows_configuration
    path: azure-mgmt-batch\azure\mgmt\batch\models\windows_configuration.py
    remote:
      branch: master
      path: azure-mgmt-batch\azure\mgmt\batch\models\windows_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batch.models.windows_configuration
references:
- fullName: azure.mgmt.batch.models.windows_configuration.WindowsConfiguration
  isExternal: false
  name: WindowsConfiguration
  parent: azure.mgmt.batch.models.windows_configuration
  uid: azure.mgmt.batch.models.windows_configuration.WindowsConfiguration
