### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.datafactory.models.distcp_settings.DistcpSettings
  fullName: azure.mgmt.datafactory.models.distcp_settings
  langs:
  - python
  module: azure.mgmt.datafactory.models.distcp_settings
  name: distcp_settings
  source:
    id: distcp_settings
    path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\distcp_settings.py
    remote:
      branch: master
      path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\distcp_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.datafactory.models.distcp_settings
references:
- fullName: azure.mgmt.datafactory.models.distcp_settings.DistcpSettings
  isExternal: false
  name: DistcpSettings
  parent: azure.mgmt.datafactory.models.distcp_settings
  uid: azure.mgmt.datafactory.models.distcp_settings.DistcpSettings
