### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.datalake.store.models.update_encryption_config_py3.UpdateEncryptionConfig
  fullName: azure.mgmt.datalake.store.models.update_encryption_config_py3
  langs:
  - python
  module: azure.mgmt.datalake.store.models.update_encryption_config_py3
  name: update_encryption_config_py3
  source:
    id: update_encryption_config_py3
    path: azure-mgmt-datalake-store\azure\mgmt\datalake\store\models\update_encryption_config_py3.py
    remote:
      branch: master
      path: azure-mgmt-datalake-store\azure\mgmt\datalake\store\models\update_encryption_config_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.datalake.store.models.update_encryption_config_py3
references:
- fullName: azure.mgmt.datalake.store.models.update_encryption_config_py3.UpdateEncryptionConfig
  isExternal: false
  name: UpdateEncryptionConfig
  parent: azure.mgmt.datalake.store.models.update_encryption_config_py3
  uid: azure.mgmt.datalake.store.models.update_encryption_config_py3.UpdateEncryptionConfig
