### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.media.models.cenc_drm_configuration.CencDrmConfiguration
  fullName: azure.mgmt.media.models.cenc_drm_configuration.CencDrmConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.media.models.cenc_drm_configuration
  name: CencDrmConfiguration
  source:
    id: CencDrmConfiguration
    path: azure-mgmt-media\azure\mgmt\media\models\cenc_drm_configuration.py
    remote:
      branch: master
      path: azure-mgmt-media\azure\mgmt\media\models\cenc_drm_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Class to specify DRM configurations of CommonEncryptionCenc scheme in

    Streaming Policy.

    '
  syntax:
    content: CencDrmConfiguration(**kwargs)
    parameters:
    - description: 'PlayReady configurations

        '
      id: play_ready
      type:
      - azure.mgmt.media.models.StreamingPolicyPlayReadyConfiguration
    - description: 'Widevine configurations

        '
      id: widevine
      type:
      - azure.mgmt.media.models.StreamingPolicyWidevineConfiguration
  type: class
  uid: azure.mgmt.media.models.cenc_drm_configuration.CencDrmConfiguration
references: []
