### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.media.models.content_key_policy_unknown_configuration.ContentKeyPolicyUnknownConfiguration
  fullName: azure.mgmt.media.models.content_key_policy_unknown_configuration
  langs:
  - python
  module: azure.mgmt.media.models.content_key_policy_unknown_configuration
  name: content_key_policy_unknown_configuration
  source:
    id: content_key_policy_unknown_configuration
    path: azure-mgmt-media\azure\mgmt\media\models\content_key_policy_unknown_configuration.py
    remote:
      branch: master
      path: azure-mgmt-media\azure\mgmt\media\models\content_key_policy_unknown_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.media.models.content_key_policy_unknown_configuration
references:
- fullName: azure.mgmt.media.models.content_key_policy_unknown_configuration.ContentKeyPolicyUnknownConfiguration
  isExternal: false
  name: ContentKeyPolicyUnknownConfiguration
  parent: azure.mgmt.media.models.content_key_policy_unknown_configuration
  uid: azure.mgmt.media.models.content_key_policy_unknown_configuration.ContentKeyPolicyUnknownConfiguration
