### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.network.v2018_06_01.models.ApplicationGatewayAutoscaleBounds
  fullName: azure.mgmt.network.v2018_06_01.models.ApplicationGatewayAutoscaleBounds
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.network.v2018_06_01.models
  name: ApplicationGatewayAutoscaleBounds
  source:
    id: ApplicationGatewayAutoscaleBounds
    path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\application_gateway_autoscale_bounds_py3.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\application_gateway_autoscale_bounds_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Application Gateway autoscale bounds on number of Application Gateway

    instance.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: 'ApplicationGatewayAutoscaleBounds(*, min: int, max: int, **kwargs) ->
      None'
    parameters:
    - description: 'Required. Lower bound on number of Application Gateway

        instances.

        '
      id: min
      type:
      - int
    - description: 'Required. Upper bound on number of Application Gateway

        instances.

        '
      id: max
      type:
      - int
  type: class
  uid: azure.mgmt.network.v2018_06_01.models.ApplicationGatewayAutoscaleBounds
references: []
