### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.monitor.operations.diagnostic_settings_category_operations.DiagnosticSettingsCategoryOperations
  fullName: azure.mgmt.monitor.operations.diagnostic_settings_category_operations
  langs:
  - python
  module: azure.mgmt.monitor.operations.diagnostic_settings_category_operations
  name: diagnostic_settings_category_operations
  source:
    id: diagnostic_settings_category_operations
    path: azure-mgmt-monitor\azure\mgmt\monitor\operations\diagnostic_settings_category_operations.py
    remote:
      branch: master
      path: azure-mgmt-monitor\azure\mgmt\monitor\operations\diagnostic_settings_category_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.monitor.operations.diagnostic_settings_category_operations
references:
- fullName: azure.mgmt.monitor.operations.diagnostic_settings_category_operations.DiagnosticSettingsCategoryOperations
  isExternal: false
  name: DiagnosticSettingsCategoryOperations
  parent: azure.mgmt.monitor.operations.diagnostic_settings_category_operations
  uid: azure.mgmt.monitor.operations.diagnostic_settings_category_operations.DiagnosticSettingsCategoryOperations
