### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.backup_configuration_info.BackupConfigurationInfo
  fullName: azure.servicefabric.models.backup_configuration_info
  langs:
  - python
  module: azure.servicefabric.models.backup_configuration_info
  name: backup_configuration_info
  source:
    id: backup_configuration_info
    path: azure-servicefabric\azure\servicefabric\models\backup_configuration_info.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\backup_configuration_info.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.backup_configuration_info
references:
- fullName: azure.servicefabric.models.backup_configuration_info.BackupConfigurationInfo
  isExternal: false
  name: BackupConfigurationInfo
  parent: azure.servicefabric.models.backup_configuration_info
  uid: azure.servicefabric.models.backup_configuration_info.BackupConfigurationInfo
