### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_health_policies.ApplicationHealthPolicies
  fullName: azure.servicefabric.models.application_health_policies
  langs:
  - python
  module: azure.servicefabric.models.application_health_policies
  name: application_health_policies
  source:
    id: application_health_policies
    path: azure-servicefabric\azure\servicefabric\models\application_health_policies.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_health_policies.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_health_policies
references:
- fullName: azure.servicefabric.models.application_health_policies.ApplicationHealthPolicies
  isExternal: false
  name: ApplicationHealthPolicies
  parent: azure.servicefabric.models.application_health_policies
  uid: azure.servicefabric.models.application_health_policies.ApplicationHealthPolicies
