### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3.WaitForReconfigurationSafetyCheck
  fullName: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3
  langs:
  - python
  module: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3
  name: wait_for_reconfiguration_safety_check_py3
  source:
    id: wait_for_reconfiguration_safety_check_py3
    path: azure-servicefabric\azure\servicefabric\models\wait_for_reconfiguration_safety_check_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\wait_for_reconfiguration_safety_check_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3
references:
- fullName: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3.WaitForReconfigurationSafetyCheck
  isExternal: false
  name: WaitForReconfigurationSafetyCheck
  parent: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3
  uid: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3.WaitForReconfigurationSafetyCheck
