### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_health_report_expired_event.ApplicationHealthReportExpiredEvent
  fullName: azure.servicefabric.models.application_health_report_expired_event
  langs:
  - python
  module: azure.servicefabric.models.application_health_report_expired_event
  name: application_health_report_expired_event
  source:
    id: application_health_report_expired_event
    path: azure-servicefabric\azure\servicefabric\models\application_health_report_expired_event.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_health_report_expired_event.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_health_report_expired_event
references:
- fullName: azure.servicefabric.models.application_health_report_expired_event.ApplicationHealthReportExpiredEvent
  isExternal: false
  name: ApplicationHealthReportExpiredEvent
  parent: azure.servicefabric.models.application_health_report_expired_event
  uid: azure.servicefabric.models.application_health_report_expired_event.ApplicationHealthReportExpiredEvent
