### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_deleted_event.ApplicationDeletedEvent
  fullName: azure.servicefabric.models.application_deleted_event
  langs:
  - python
  module: azure.servicefabric.models.application_deleted_event
  name: application_deleted_event
  source:
    id: application_deleted_event
    path: azure-servicefabric\azure\servicefabric\models\application_deleted_event.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_deleted_event.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_deleted_event
references:
- fullName: azure.servicefabric.models.application_deleted_event.ApplicationDeletedEvent
  isExternal: false
  name: ApplicationDeletedEvent
  parent: azure.servicefabric.models.application_deleted_event
  uid: azure.servicefabric.models.application_deleted_event.ApplicationDeletedEvent
