### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_backup_entity.ApplicationBackupEntity
  fullName: azure.servicefabric.models.application_backup_entity
  langs:
  - python
  module: azure.servicefabric.models.application_backup_entity
  name: application_backup_entity
  source:
    id: application_backup_entity
    path: azure-servicefabric\azure\servicefabric\models\application_backup_entity.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_backup_entity.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_backup_entity
references:
- fullName: azure.servicefabric.models.application_backup_entity.ApplicationBackupEntity
  isExternal: false
  name: ApplicationBackupEntity
  parent: azure.servicefabric.models.application_backup_entity
  uid: azure.servicefabric.models.application_backup_entity.ApplicationBackupEntity
