### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.unprovision_application_type_description_info.UnprovisionApplicationTypeDescriptionInfo
  fullName: azure.servicefabric.models.unprovision_application_type_description_info
  langs:
  - python
  module: azure.servicefabric.models.unprovision_application_type_description_info
  name: unprovision_application_type_description_info
  source:
    id: unprovision_application_type_description_info
    path: azure-servicefabric\azure\servicefabric\models\unprovision_application_type_description_info.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\unprovision_application_type_description_info.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.unprovision_application_type_description_info
references:
- fullName: azure.servicefabric.models.unprovision_application_type_description_info.UnprovisionApplicationTypeDescriptionInfo
  isExternal: false
  name: UnprovisionApplicationTypeDescriptionInfo
  parent: azure.servicefabric.models.unprovision_application_type_description_info
  uid: azure.servicefabric.models.unprovision_application_type_description_info.UnprovisionApplicationTypeDescriptionInfo
