### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.servicefabric.models.create_compose_deployment_description.CreateComposeDeploymentDescription
  fullName: azure.servicefabric.models.create_compose_deployment_description.CreateComposeDeploymentDescription
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.servicefabric.models.create_compose_deployment_description
  name: CreateComposeDeploymentDescription
  source:
    id: CreateComposeDeploymentDescription
    path: azure-servicefabric\azure\servicefabric\models\create_compose_deployment_description.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\create_compose_deployment_description.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Defines description for creating a Service Fabric compose deployment.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: CreateComposeDeploymentDescription(**kwargs)
    parameters:
    - description: 'Required. The name of the deployment.

        '
      id: deployment_name
      type:
      - str
    - description: 'Required. The content of the compose file

        that describes the deployment to create.

        '
      id: compose_file_content
      type:
      - str
    - description: 'Credential information to connect to container

        registry.

        '
      id: registry_credential
      type:
      - azure.servicefabric.models.RegistryCredential
  type: class
  uid: azure.servicefabric.models.create_compose_deployment_description.CreateComposeDeploymentDescription
references: []
