### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_type_image_store_path.ApplicationTypeImageStorePath
  fullName: azure.servicefabric.models.application_type_image_store_path
  langs:
  - python
  module: azure.servicefabric.models.application_type_image_store_path
  name: application_type_image_store_path
  source:
    id: application_type_image_store_path
    path: azure-servicefabric\azure\servicefabric\models\application_type_image_store_path.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_type_image_store_path.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_type_image_store_path
references:
- fullName: azure.servicefabric.models.application_type_image_store_path.ApplicationTypeImageStorePath
  isExternal: false
  name: ApplicationTypeImageStorePath
  parent: azure.servicefabric.models.application_type_image_store_path
  uid: azure.servicefabric.models.application_type_image_store_path.ApplicationTypeImageStorePath
