### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_upgrade_description.ApplicationUpgradeDescription
  fullName: azure.servicefabric.models.application_upgrade_description
  langs:
  - python
  module: azure.servicefabric.models.application_upgrade_description
  name: application_upgrade_description
  source:
    id: application_upgrade_description
    path: azure-servicefabric\azure\servicefabric\models\application_upgrade_description.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_upgrade_description.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_upgrade_description
references:
- fullName: azure.servicefabric.models.application_upgrade_description.ApplicationUpgradeDescription
  isExternal: false
  name: ApplicationUpgradeDescription
  parent: azure.servicefabric.models.application_upgrade_description
  uid: azure.servicefabric.models.application_upgrade_description.ApplicationUpgradeDescription
