### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_resource_description.ApplicationResourceDescription
  fullName: azure.servicefabric.models.application_resource_description
  langs:
  - python
  module: azure.servicefabric.models.application_resource_description
  name: application_resource_description
  source:
    id: application_resource_description
    path: azure-servicefabric\azure\servicefabric\models\application_resource_description.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_resource_description.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_resource_description
references:
- fullName: azure.servicefabric.models.application_resource_description.ApplicationResourceDescription
  isExternal: false
  name: ApplicationResourceDescription
  parent: azure.servicefabric.models.application_resource_description
  uid: azure.servicefabric.models.application_resource_description.ApplicationResourceDescription
