### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.partition_backup_configuration_info.PartitionBackupConfigurationInfo
  fullName: azure.servicefabric.models.partition_backup_configuration_info
  langs:
  - python
  module: azure.servicefabric.models.partition_backup_configuration_info
  name: partition_backup_configuration_info
  source:
    id: partition_backup_configuration_info
    path: azure-servicefabric\azure\servicefabric\models\partition_backup_configuration_info.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\partition_backup_configuration_info.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.partition_backup_configuration_info
references:
- fullName: azure.servicefabric.models.partition_backup_configuration_info.PartitionBackupConfigurationInfo
  isExternal: false
  name: PartitionBackupConfigurationInfo
  parent: azure.servicefabric.models.partition_backup_configuration_info
  uid: azure.servicefabric.models.partition_backup_configuration_info.PartitionBackupConfigurationInfo
