### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.external_store_provision_application_type_description_py3.ExternalStoreProvisionApplicationTypeDescription
  fullName: azure.servicefabric.models.external_store_provision_application_type_description_py3
  langs:
  - python
  module: azure.servicefabric.models.external_store_provision_application_type_description_py3
  name: external_store_provision_application_type_description_py3
  source:
    id: external_store_provision_application_type_description_py3
    path: azure-servicefabric\azure\servicefabric\models\external_store_provision_application_type_description_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\external_store_provision_application_type_description_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.external_store_provision_application_type_description_py3
references:
- fullName: azure.servicefabric.models.external_store_provision_application_type_description_py3.ExternalStoreProvisionApplicationTypeDescription
  isExternal: false
  name: ExternalStoreProvisionApplicationTypeDescription
  parent: azure.servicefabric.models.external_store_provision_application_type_description_py3
  uid: azure.servicefabric.models.external_store_provision_application_type_description_py3.ExternalStoreProvisionApplicationTypeDescription
