### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.cluster_configuration.ClusterConfiguration
  fullName: azure.servicefabric.models.cluster_configuration
  langs:
  - python
  module: azure.servicefabric.models.cluster_configuration
  name: cluster_configuration
  source:
    id: cluster_configuration
    path: azure-servicefabric\azure\servicefabric\models\cluster_configuration.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\cluster_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.cluster_configuration
references:
- fullName: azure.servicefabric.models.cluster_configuration.ClusterConfiguration
  isExternal: false
  name: ClusterConfiguration
  parent: azure.servicefabric.models.cluster_configuration
  uid: azure.servicefabric.models.cluster_configuration.ClusterConfiguration
