### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.horovod_settings.HorovodSettings
  fullName: azure.mgmt.batchai.models.horovod_settings
  langs:
  - python
  module: azure.mgmt.batchai.models.horovod_settings
  name: horovod_settings
  source:
    id: horovod_settings
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\horovod_settings.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\horovod_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.horovod_settings
references:
- fullName: azure.mgmt.batchai.models.horovod_settings.HorovodSettings
  isExternal: false
  name: HorovodSettings
  parent: azure.mgmt.batchai.models.horovod_settings
  uid: azure.mgmt.batchai.models.horovod_settings.HorovodSettings
