### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.logic.models.batch_configuration_paged.BatchConfigurationPaged
  fullName: azure.mgmt.logic.models.batch_configuration_paged
  langs:
  - python
  module: azure.mgmt.logic.models.batch_configuration_paged
  name: batch_configuration_paged
  source:
    id: batch_configuration_paged
    path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration_paged.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration_paged.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.logic.models.batch_configuration_paged
references:
- fullName: azure.mgmt.logic.models.batch_configuration_paged.BatchConfigurationPaged
  isExternal: false
  name: BatchConfigurationPaged
  parent: azure.mgmt.logic.models.batch_configuration_paged
  uid: azure.mgmt.logic.models.batch_configuration_paged.BatchConfigurationPaged
