### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.logic.models.batch_configuration_properties.BatchConfigurationProperties
  fullName: azure.mgmt.logic.models.batch_configuration_properties
  langs:
  - python
  module: azure.mgmt.logic.models.batch_configuration_properties
  name: batch_configuration_properties
  source:
    id: batch_configuration_properties
    path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration_properties.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration_properties.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.logic.models.batch_configuration_properties
references:
- fullName: azure.mgmt.logic.models.batch_configuration_properties.BatchConfigurationProperties
  isExternal: false
  name: BatchConfigurationProperties
  parent: azure.mgmt.logic.models.batch_configuration_properties
  uid: azure.mgmt.logic.models.batch_configuration_properties.BatchConfigurationProperties
