### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.logic.models.batch_configuration_py3.BatchConfiguration
  fullName: azure.mgmt.logic.models.batch_configuration_py3
  langs:
  - python
  module: azure.mgmt.logic.models.batch_configuration_py3
  name: batch_configuration_py3
  source:
    id: batch_configuration_py3
    path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration_py3.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\models\batch_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.logic.models.batch_configuration_py3
references:
- fullName: azure.mgmt.logic.models.batch_configuration_py3.BatchConfiguration
  isExternal: false
  name: BatchConfiguration
  parent: azure.mgmt.logic.models.batch_configuration_py3
  uid: azure.mgmt.logic.models.batch_configuration_py3.BatchConfiguration
