### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.logic.operations.integration_account_batch_configurations_operations.IntegrationAccountBatchConfigurationsOperations
  fullName: azure.mgmt.logic.operations.integration_account_batch_configurations_operations
  langs:
  - python
  module: azure.mgmt.logic.operations.integration_account_batch_configurations_operations
  name: integration_account_batch_configurations_operations
  source:
    id: integration_account_batch_configurations_operations
    path: azure-mgmt-logic\azure\mgmt\logic\operations\integration_account_batch_configurations_operations.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\operations\integration_account_batch_configurations_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.logic.operations.integration_account_batch_configurations_operations
references:
- fullName: azure.mgmt.logic.operations.integration_account_batch_configurations_operations.IntegrationAccountBatchConfigurationsOperations
  isExternal: false
  name: IntegrationAccountBatchConfigurationsOperations
  parent: azure.mgmt.logic.operations.integration_account_batch_configurations_operations
  uid: azure.mgmt.logic.operations.integration_account_batch_configurations_operations.IntegrationAccountBatchConfigurationsOperations
