### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.media.models.content_key_policy_widevine_configuration.ContentKeyPolicyWidevineConfiguration
  fullName: azure.mgmt.media.models.content_key_policy_widevine_configuration.ContentKeyPolicyWidevineConfiguration
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.serialization.Model
    type: azure.mgmt.media.models.content_key_policy_configuration.ContentKeyPolicyConfiguration
  langs:
  - python
  module: azure.mgmt.media.models.content_key_policy_widevine_configuration
  name: ContentKeyPolicyWidevineConfiguration
  source:
    id: ContentKeyPolicyWidevineConfiguration
    path: azure-mgmt-media\azure\mgmt\media\models\content_key_policy_widevine_configuration.py
    remote:
      branch: master
      path: azure-mgmt-media\azure\mgmt\media\models\content_key_policy_widevine_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Specifies a configuration for Widevine licenses.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: ContentKeyPolicyWidevineConfiguration(**kwargs)
    parameters:
    - description: 'Required. Constant filled by server.

        '
      id: odatatype
      type:
      - str
    - description: 'Required. The Widevine template.

        '
      id: widevine_template
      type:
      - str
  type: class
  uid: azure.mgmt.media.models.content_key_policy_widevine_configuration.ContentKeyPolicyWidevineConfiguration
references: []
