### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.media.models.streaming_policy_widevine_configuration.StreamingPolicyWidevineConfiguration
  fullName: azure.mgmt.media.models.streaming_policy_widevine_configuration
  langs:
  - python
  module: azure.mgmt.media.models.streaming_policy_widevine_configuration
  name: streaming_policy_widevine_configuration
  source:
    id: streaming_policy_widevine_configuration
    path: azure-mgmt-media\azure\mgmt\media\models\streaming_policy_widevine_configuration.py
    remote:
      branch: master
      path: azure-mgmt-media\azure\mgmt\media\models\streaming_policy_widevine_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.media.models.streaming_policy_widevine_configuration
references:
- fullName: azure.mgmt.media.models.streaming_policy_widevine_configuration.StreamingPolicyWidevineConfiguration
  isExternal: false
  name: StreamingPolicyWidevineConfiguration
  parent: azure.mgmt.media.models.streaming_policy_widevine_configuration
  uid: azure.mgmt.media.models.streaming_policy_widevine_configuration.StreamingPolicyWidevineConfiguration
