### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.advisor.models.config_data_properties.ConfigDataProperties
  fullName: azure.mgmt.advisor.models.config_data_properties
  langs:
  - python
  module: azure.mgmt.advisor.models.config_data_properties
  name: config_data_properties
  source:
    id: config_data_properties
    path: azure-mgmt-advisor\azure\mgmt\advisor\models\config_data_properties.py
    remote:
      branch: master
      path: azure-mgmt-advisor\azure\mgmt\advisor\models\config_data_properties.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.advisor.models.config_data_properties
references:
- fullName: azure.mgmt.advisor.models.config_data_properties.ConfigDataProperties
  isExternal: false
  name: ConfigDataProperties
  parent: azure.mgmt.advisor.models.config_data_properties
  uid: azure.mgmt.advisor.models.config_data_properties.ConfigDataProperties
