### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: uamqp.c_uamqp.HTTPProxyConfig
  fullName: uamqp.c_uamqp.HTTPProxyConfig
  inheritance:
  - type: builtins.object
  langs:
  - python
  module: uamqp.c_uamqp
  name: HTTPProxyConfig
  source:
    id: HTTPProxyConfig
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-uamqp-python.git
    startLine: null
  summary: '





    '
  syntax: {}
  type: class
  uid: uamqp.c_uamqp.HTTPProxyConfig
references: []
