### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.web.models.app_service_environment_patch_resource.AppServiceEnvironmentPatchResource
  fullName: azure.mgmt.web.models.app_service_environment_patch_resource
  langs:
  - python
  module: azure.mgmt.web.models.app_service_environment_patch_resource
  name: app_service_environment_patch_resource
  source:
    id: app_service_environment_patch_resource
    path: azure-mgmt-web\azure\mgmt\web\models\app_service_environment_patch_resource.py
    remote:
      branch: master
      path: azure-mgmt-web\azure\mgmt\web\models\app_service_environment_patch_resource.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.web.models.app_service_environment_patch_resource
references:
- fullName: azure.mgmt.web.models.app_service_environment_patch_resource.AppServiceEnvironmentPatchResource
  isExternal: false
  name: AppServiceEnvironmentPatchResource
  parent: azure.mgmt.web.models.app_service_environment_patch_resource
  uid: azure.mgmt.web.models.app_service_environment_patch_resource.AppServiceEnvironmentPatchResource
