### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.cognitiveservices.search.entitysearch.entity_search_api.EntitySearchAPIConfiguration
  fullName: azure.cognitiveservices.search.entitysearch.entity_search_api.EntitySearchAPIConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.configuration.Configuration
  langs:
  - python
  module: azure.cognitiveservices.search.entitysearch.entity_search_api
  name: EntitySearchAPIConfiguration
  source:
    id: EntitySearchAPIConfiguration
    path: azure-cognitiveservices-search-entitysearch\azure\cognitiveservices\search\entitysearch\entity_search_api.py
    remote:
      branch: master
      path: azure-cognitiveservices-search-entitysearch\azure\cognitiveservices\search\entitysearch\entity_search_api.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 19
  summary: 'Configuration for EntitySearchAPI

    Note that all parameters used to create this instance are saved as instance

    attributes.

    '
  syntax:
    content: EntitySearchAPIConfiguration(credentials, base_url=None)
    parameters:
    - description: 'Subscription credentials which uniquely identify

        client subscription.

        '
      id: credentials
      type:
      - None
    - description: 'Service URL

        '
      id: base_url
      type:
      - str
  type: class
  uid: azure.cognitiveservices.search.entitysearch.entity_search_api.EntitySearchAPIConfiguration
references: []
