### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.batch.models.task_container_settings.TaskContainerSettings
  fullName: azure.batch.models.task_container_settings
  langs:
  - python
  module: azure.batch.models.task_container_settings
  name: task_container_settings
  source:
    id: task_container_settings
    path: azure-batch\azure\batch\models\task_container_settings.py
    remote:
      branch: master
      path: azure-batch\azure\batch\models\task_container_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.batch.models.task_container_settings
references:
- fullName: azure.batch.models.task_container_settings.TaskContainerSettings
  isExternal: false
  name: TaskContainerSettings
  parent: azure.batch.models.task_container_settings
  uid: azure.batch.models.task_container_settings.TaskContainerSettings
