### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item.MonitorConfigCustomHeadersItem
  fullName: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item
  langs:
  - python
  module: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item
  name: monitor_config_custom_headers_item
  source:
    id: monitor_config_custom_headers_item
    path: azure-mgmt-trafficmanager\azure\mgmt\trafficmanager\models\monitor_config_custom_headers_item.py
    remote:
      branch: master
      path: azure-mgmt-trafficmanager\azure\mgmt\trafficmanager\models\monitor_config_custom_headers_item.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item
references:
- fullName: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item.MonitorConfigCustomHeadersItem
  isExternal: false
  name: MonitorConfigCustomHeadersItem
  parent: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item
  uid: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item.MonitorConfigCustomHeadersItem
