### YamlMime:UniversalReference
api_name: []
items:
- children:
  - uamqp.c_uamqp.TLSIOConfig.set_proxy_config
  class: uamqp.c_uamqp.TLSIOConfig
  fullName: uamqp.c_uamqp.TLSIOConfig
  inheritance:
  - type: builtins.object
  langs:
  - python
  module: uamqp.c_uamqp
  name: TLSIOConfig
  source:
    id: TLSIOConfig
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-uamqp-python.git
    startLine: null
  summary: '


    '
  syntax: {}
  type: class
  uid: uamqp.c_uamqp.TLSIOConfig
- class: uamqp.c_uamqp.TLSIOConfig
  fullName: uamqp.c_uamqp.TLSIOConfig.set_proxy_config
  langs:
  - python
  module: uamqp.c_uamqp
  name: set_proxy_config
  source:
    id: set_proxy_config
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-uamqp-python.git
    startLine: null
  syntax: {}
  type: method
  uid: uamqp.c_uamqp.TLSIOConfig.set_proxy_config
references:
- fullName: uamqp.c_uamqp.TLSIOConfig.set_proxy_config
  isExternal: false
  name: set_proxy_config
  parent: uamqp.c_uamqp.TLSIOConfig
  uid: uamqp.c_uamqp.TLSIOConfig.set_proxy_config
