### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.cognitiveservices.vision.customvision.training.models.project_settings_py3.ProjectSettings
  fullName: azure.cognitiveservices.vision.customvision.training.models.project_settings_py3
  langs:
  - python
  module: azure.cognitiveservices.vision.customvision.training.models.project_settings_py3
  name: project_settings_py3
  source:
    id: project_settings_py3
    path: azure-cognitiveservices-vision-customvision\azure\cognitiveservices\vision\customvision\training\models\project_settings_py3.py
    remote:
      branch: master
      path: azure-cognitiveservices-vision-customvision\azure\cognitiveservices\vision\customvision\training\models\project_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.cognitiveservices.vision.customvision.training.models.project_settings_py3
references:
- fullName: azure.cognitiveservices.vision.customvision.training.models.project_settings_py3.ProjectSettings
  isExternal: false
  name: ProjectSettings
  parent: azure.cognitiveservices.vision.customvision.training.models.project_settings_py3
  uid: azure.cognitiveservices.vision.customvision.training.models.project_settings_py3.ProjectSettings
