### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.policyinsights.policy_insights_client.PolicyInsightsClientConfiguration
  fullName: azure.mgmt.policyinsights.policy_insights_client.PolicyInsightsClientConfiguration
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.configuration.Configuration
    type: msrestazure.azure_configuration.AzureConfiguration
  langs:
  - python
  module: azure.mgmt.policyinsights.policy_insights_client
  name: PolicyInsightsClientConfiguration
  source:
    id: PolicyInsightsClientConfiguration
    path: azure-mgmt-policyinsights\azure\mgmt\policyinsights\policy_insights_client.py
    remote:
      branch: master
      path: azure-mgmt-policyinsights\azure\mgmt\policyinsights\policy_insights_client.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 22
  summary: 'Configuration for PolicyInsightsClient

    Note that all parameters used to create this instance are saved as instance

    attributes.

    '
  syntax:
    content: PolicyInsightsClientConfiguration(credentials, base_url=None)
    parameters:
    - description: 'Credentials needed for the client to connect to Azure.

        '
      id: credentials
      type:
      - msrestazure.azure_active_directory
    - description: 'Service URL

        '
      id: base_url
      type:
      - str
  type: class
  uid: azure.mgmt.policyinsights.policy_insights_client.PolicyInsightsClientConfiguration
references: []
