### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batch.models.pool_endpoint_configuration.PoolEndpointConfiguration
  fullName: azure.mgmt.batch.models.pool_endpoint_configuration
  langs:
  - python
  module: azure.mgmt.batch.models.pool_endpoint_configuration
  name: pool_endpoint_configuration
  source:
    id: pool_endpoint_configuration
    path: azure-mgmt-batch\azure\mgmt\batch\models\pool_endpoint_configuration.py
    remote:
      branch: master
      path: azure-mgmt-batch\azure\mgmt\batch\models\pool_endpoint_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batch.models.pool_endpoint_configuration
references:
- fullName: azure.mgmt.batch.models.pool_endpoint_configuration.PoolEndpointConfiguration
  isExternal: false
  name: PoolEndpointConfiguration
  parent: azure.mgmt.batch.models.pool_endpoint_configuration
  uid: azure.mgmt.batch.models.pool_endpoint_configuration.PoolEndpointConfiguration
