### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicefabric.models.application_type_resource.ApplicationTypeResource
  fullName: azure.mgmt.servicefabric.models.application_type_resource
  langs:
  - python
  module: azure.mgmt.servicefabric.models.application_type_resource
  name: application_type_resource
  source:
    id: application_type_resource
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_type_resource.py
    remote:
      branch: master
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_type_resource.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicefabric.models.application_type_resource
references:
- fullName: azure.mgmt.servicefabric.models.application_type_resource.ApplicationTypeResource
  isExternal: false
  name: ApplicationTypeResource
  parent: azure.mgmt.servicefabric.models.application_type_resource
  uid: azure.mgmt.servicefabric.models.application_type_resource.ApplicationTypeResource
