### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resource.managedapplications.models.application_patchable.ApplicationPatchable
  fullName: azure.mgmt.resource.managedapplications.models.application_patchable
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_patchable
  name: application_patchable
  source:
    id: application_patchable
    path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\models\application_patchable.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\models\application_patchable.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.resource.managedapplications.models.application_patchable
references:
- fullName: azure.mgmt.resource.managedapplications.models.application_patchable.ApplicationPatchable
  isExternal: false
  name: ApplicationPatchable
  parent: azure.mgmt.resource.managedapplications.models.application_patchable
  uid: azure.mgmt.resource.managedapplications.models.application_patchable.ApplicationPatchable
