### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resource.managedapplications.models.application_definition_py3.ApplicationDefinition
  fullName: azure.mgmt.resource.managedapplications.models.application_definition_py3
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_definition_py3
  name: application_definition_py3
  source:
    id: application_definition_py3
    path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\models\application_definition_py3.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\models\application_definition_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.resource.managedapplications.models.application_definition_py3
references:
- fullName: azure.mgmt.resource.managedapplications.models.application_definition_py3.ApplicationDefinition
  isExternal: false
  name: ApplicationDefinition
  parent: azure.mgmt.resource.managedapplications.models.application_definition_py3
  uid: azure.mgmt.resource.managedapplications.models.application_definition_py3.ApplicationDefinition
