### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicebus.models.migration_config_properties_py3.MigrationConfigProperties
  fullName: azure.mgmt.servicebus.models.migration_config_properties_py3
  langs:
  - python
  module: azure.mgmt.servicebus.models.migration_config_properties_py3
  name: migration_config_properties_py3
  source:
    id: migration_config_properties_py3
    path: azure-mgmt-servicebus\azure\mgmt\servicebus\models\migration_config_properties_py3.py
    remote:
      branch: master
      path: azure-mgmt-servicebus\azure\mgmt\servicebus\models\migration_config_properties_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicebus.models.migration_config_properties_py3
references:
- fullName: azure.mgmt.servicebus.models.migration_config_properties_py3.MigrationConfigProperties
  isExternal: false
  name: MigrationConfigProperties
  parent: azure.mgmt.servicebus.models.migration_config_properties_py3
  uid: azure.mgmt.servicebus.models.migration_config_properties_py3.MigrationConfigProperties
