### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3.BackupResourceConfig
  fullName: azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3
  langs:
  - python
  module: azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3
  name: backup_resource_config_py3
  source:
    id: backup_resource_config_py3
    path: azure-mgmt-recoveryservicesbackup\azure\mgmt\recoveryservicesbackup\models\backup_resource_config_py3.py
    remote:
      branch: master
      path: azure-mgmt-recoveryservicesbackup\azure\mgmt\recoveryservicesbackup\models\backup_resource_config_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3
references:
- fullName: azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3.BackupResourceConfig
  isExternal: false
  name: BackupResourceConfig
  parent: azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3
  uid: azure.mgmt.recoveryservicesbackup.models.backup_resource_config_py3.BackupResourceConfig
