### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.datafactory.models.redirect_incompatible_row_settings.RedirectIncompatibleRowSettings
  fullName: azure.mgmt.datafactory.models.redirect_incompatible_row_settings
  langs:
  - python
  module: azure.mgmt.datafactory.models.redirect_incompatible_row_settings
  name: redirect_incompatible_row_settings
  source:
    id: redirect_incompatible_row_settings
    path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\redirect_incompatible_row_settings.py
    remote:
      branch: master
      path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\redirect_incompatible_row_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.datafactory.models.redirect_incompatible_row_settings
references:
- fullName: azure.mgmt.datafactory.models.redirect_incompatible_row_settings.RedirectIncompatibleRowSettings
  isExternal: false
  name: RedirectIncompatibleRowSettings
  parent: azure.mgmt.datafactory.models.redirect_incompatible_row_settings
  uid: azure.mgmt.datafactory.models.redirect_incompatible_row_settings.RedirectIncompatibleRowSettings
