### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.datafactory.models.staging_settings.StagingSettings
  fullName: azure.mgmt.datafactory.models.staging_settings
  langs:
  - python
  module: azure.mgmt.datafactory.models.staging_settings
  name: staging_settings
  source:
    id: staging_settings
    path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\staging_settings.py
    remote:
      branch: master
      path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\staging_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.datafactory.models.staging_settings
references:
- fullName: azure.mgmt.datafactory.models.staging_settings.StagingSettings
  isExternal: false
  name: StagingSettings
  parent: azure.mgmt.datafactory.models.staging_settings
  uid: azure.mgmt.datafactory.models.staging_settings.StagingSettings
