### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicebus.operations.migration_configs_operations.MigrationConfigsOperations
  fullName: azure.mgmt.servicebus.operations.migration_configs_operations
  langs:
  - python
  module: azure.mgmt.servicebus.operations.migration_configs_operations
  name: migration_configs_operations
  source:
    id: migration_configs_operations
    path: azure-mgmt-servicebus\azure\mgmt\servicebus\operations\migration_configs_operations.py
    remote:
      branch: master
      path: azure-mgmt-servicebus\azure\mgmt\servicebus\operations\migration_configs_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicebus.operations.migration_configs_operations
references:
- fullName: azure.mgmt.servicebus.operations.migration_configs_operations.MigrationConfigsOperations
  isExternal: false
  name: MigrationConfigsOperations
  parent: azure.mgmt.servicebus.operations.migration_configs_operations
  uid: azure.mgmt.servicebus.operations.migration_configs_operations.MigrationConfigsOperations
