### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicebus.models.migration_config_properties_paged.MigrationConfigPropertiesPaged
  fullName: azure.mgmt.servicebus.models.migration_config_properties_paged
  langs:
  - python
  module: azure.mgmt.servicebus.models.migration_config_properties_paged
  name: migration_config_properties_paged
  source:
    id: migration_config_properties_paged
    path: azure-mgmt-servicebus\azure\mgmt\servicebus\models\migration_config_properties_paged.py
    remote:
      branch: master
      path: azure-mgmt-servicebus\azure\mgmt\servicebus\models\migration_config_properties_paged.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicebus.models.migration_config_properties_paged
references:
- fullName: azure.mgmt.servicebus.models.migration_config_properties_paged.MigrationConfigPropertiesPaged
  isExternal: false
  name: MigrationConfigPropertiesPaged
  parent: azure.mgmt.servicebus.models.migration_config_properties_paged
  uid: azure.mgmt.servicebus.models.migration_config_properties_paged.MigrationConfigPropertiesPaged
