### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_backup_configuration_info.ApplicationBackupConfigurationInfo
  fullName: azure.servicefabric.models.application_backup_configuration_info
  langs:
  - python
  module: azure.servicefabric.models.application_backup_configuration_info
  name: application_backup_configuration_info
  source:
    id: application_backup_configuration_info
    path: azure-servicefabric\azure\servicefabric\models\application_backup_configuration_info.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_backup_configuration_info.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_backup_configuration_info
references:
- fullName: azure.servicefabric.models.application_backup_configuration_info.ApplicationBackupConfigurationInfo
  isExternal: false
  name: ApplicationBackupConfigurationInfo
  parent: azure.servicefabric.models.application_backup_configuration_info
  uid: azure.servicefabric.models.application_backup_configuration_info.ApplicationBackupConfigurationInfo
