### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.paged_application_type_info_list_py3.PagedApplicationTypeInfoList
  fullName: azure.servicefabric.models.paged_application_type_info_list_py3
  langs:
  - python
  module: azure.servicefabric.models.paged_application_type_info_list_py3
  name: paged_application_type_info_list_py3
  source:
    id: paged_application_type_info_list_py3
    path: azure-servicefabric\azure\servicefabric\models\paged_application_type_info_list_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\paged_application_type_info_list_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.paged_application_type_info_list_py3
references:
- fullName: azure.servicefabric.models.paged_application_type_info_list_py3.PagedApplicationTypeInfoList
  isExternal: false
  name: PagedApplicationTypeInfoList
  parent: azure.servicefabric.models.paged_application_type_info_list_py3
  uid: azure.servicefabric.models.paged_application_type_info_list_py3.PagedApplicationTypeInfoList
