### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_parameter.ApplicationParameter
  fullName: azure.servicefabric.models.application_parameter
  langs:
  - python
  module: azure.servicefabric.models.application_parameter
  name: application_parameter
  source:
    id: application_parameter
    path: azure-servicefabric\azure\servicefabric\models\application_parameter.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_parameter.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_parameter
references:
- fullName: azure.servicefabric.models.application_parameter.ApplicationParameter
  isExternal: false
  name: ApplicationParameter
  parent: azure.servicefabric.models.application_parameter
  uid: azure.servicefabric.models.application_parameter.ApplicationParameter
