### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.deployed_application_health_state_filter.DeployedApplicationHealthStateFilter
  fullName: azure.servicefabric.models.deployed_application_health_state_filter
  langs:
  - python
  module: azure.servicefabric.models.deployed_application_health_state_filter
  name: deployed_application_health_state_filter
  source:
    id: deployed_application_health_state_filter
    path: azure-servicefabric\azure\servicefabric\models\deployed_application_health_state_filter.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\deployed_application_health_state_filter.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.deployed_application_health_state_filter
references:
- fullName: azure.servicefabric.models.deployed_application_health_state_filter.DeployedApplicationHealthStateFilter
  isExternal: false
  name: DeployedApplicationHealthStateFilter
  parent: azure.servicefabric.models.deployed_application_health_state_filter
  uid: azure.servicefabric.models.deployed_application_health_state_filter.DeployedApplicationHealthStateFilter
