### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.application_type_health_policy_map_item.ApplicationTypeHealthPolicyMapItem
  fullName: azure.servicefabric.models.application_type_health_policy_map_item
  langs:
  - python
  module: azure.servicefabric.models.application_type_health_policy_map_item
  name: application_type_health_policy_map_item
  source:
    id: application_type_health_policy_map_item
    path: azure-servicefabric\azure\servicefabric\models\application_type_health_policy_map_item.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_type_health_policy_map_item.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.application_type_health_policy_map_item
references:
- fullName: azure.servicefabric.models.application_type_health_policy_map_item.ApplicationTypeHealthPolicyMapItem
  isExternal: false
  name: ApplicationTypeHealthPolicyMapItem
  parent: azure.servicefabric.models.application_type_health_policy_map_item
  uid: azure.servicefabric.models.application_type_health_policy_map_item.ApplicationTypeHealthPolicyMapItem
