### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.reconfiguration_information.ReconfigurationInformation
  fullName: azure.servicefabric.models.reconfiguration_information
  langs:
  - python
  module: azure.servicefabric.models.reconfiguration_information
  name: reconfiguration_information
  source:
    id: reconfiguration_information
    path: azure-servicefabric\azure\servicefabric\models\reconfiguration_information.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\reconfiguration_information.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.reconfiguration_information
references:
- fullName: azure.servicefabric.models.reconfiguration_information.ReconfigurationInformation
  isExternal: false
  name: ReconfigurationInformation
  parent: azure.servicefabric.models.reconfiguration_information
  uid: azure.servicefabric.models.reconfiguration_information.ReconfigurationInformation
