### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.partition_reconfiguration_completed_event.PartitionReconfigurationCompletedEvent
  fullName: azure.servicefabric.models.partition_reconfiguration_completed_event
  langs:
  - python
  module: azure.servicefabric.models.partition_reconfiguration_completed_event
  name: partition_reconfiguration_completed_event
  source:
    id: partition_reconfiguration_completed_event
    path: azure-servicefabric\azure\servicefabric\models\partition_reconfiguration_completed_event.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\partition_reconfiguration_completed_event.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.partition_reconfiguration_completed_event
references:
- fullName: azure.servicefabric.models.partition_reconfiguration_completed_event.PartitionReconfigurationCompletedEvent
  isExternal: false
  name: PartitionReconfigurationCompletedEvent
  parent: azure.servicefabric.models.partition_reconfiguration_completed_event
  uid: azure.servicefabric.models.partition_reconfiguration_completed_event.PartitionReconfigurationCompletedEvent
