### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.cluster_configuration_py3.ClusterConfiguration
  fullName: azure.servicefabric.models.cluster_configuration_py3
  langs:
  - python
  module: azure.servicefabric.models.cluster_configuration_py3
  name: cluster_configuration_py3
  source:
    id: cluster_configuration_py3
    path: azure-servicefabric\azure\servicefabric\models\cluster_configuration_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\cluster_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.cluster_configuration_py3
references:
- fullName: azure.servicefabric.models.cluster_configuration_py3.ClusterConfiguration
  isExternal: false
  name: ClusterConfiguration
  parent: azure.servicefabric.models.cluster_configuration_py3
  uid: azure.servicefabric.models.cluster_configuration_py3.ClusterConfiguration
