### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item.MonitorConfigCustomHeadersItem
  fullName: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item.MonitorConfigCustomHeadersItem
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item
  name: MonitorConfigCustomHeadersItem
  source:
    id: MonitorConfigCustomHeadersItem
    path: azure-mgmt-trafficmanager\azure\mgmt\trafficmanager\models\monitor_config_custom_headers_item.py
    remote:
      branch: master
      path: azure-mgmt-trafficmanager\azure\mgmt\trafficmanager\models\monitor_config_custom_headers_item.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Custom header name and value.

    '
  syntax:
    content: MonitorConfigCustomHeadersItem(**kwargs)
    parameters:
    - description: 'Header name.

        '
      id: name
      type:
      - str
    - description: 'Header value.

        '
      id: value
      type:
      - str
  type: class
  uid: azure.mgmt.trafficmanager.models.monitor_config_custom_headers_item.MonitorConfigCustomHeadersItem
references: []
