### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.sql.models.elastic_pool_per_database_settings.ElasticPoolPerDatabaseSettings
  fullName: azure.mgmt.sql.models.elastic_pool_per_database_settings.ElasticPoolPerDatabaseSettings
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.sql.models.elastic_pool_per_database_settings
  name: ElasticPoolPerDatabaseSettings
  source:
    id: ElasticPoolPerDatabaseSettings
    path: azure-mgmt-sql\azure\mgmt\sql\models\elastic_pool_per_database_settings.py
    remote:
      branch: master
      path: azure-mgmt-sql\azure\mgmt\sql\models\elastic_pool_per_database_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Per database settings of an elastic pool.

    '
  syntax:
    content: ElasticPoolPerDatabaseSettings(**kwargs)
    parameters:
    - description: 'The minimum capacity all databases are guaranteed.

        '
      id: min_capacity
      type:
      - float
    - description: 'The maximum capacity any one database can consume.

        '
      id: max_capacity
      type:
      - float
  type: class
  uid: azure.mgmt.sql.models.elastic_pool_per_database_settings.ElasticPoolPerDatabaseSettings
references: []
