### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.eventgrid.event_grid_management_client.EventGridManagementClientConfiguration
  fullName: azure.mgmt.eventgrid.event_grid_management_client.EventGridManagementClientConfiguration
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.configuration.Configuration
    type: msrestazure.azure_configuration.AzureConfiguration
  langs:
  - python
  module: azure.mgmt.eventgrid.event_grid_management_client
  name: EventGridManagementClientConfiguration
  source:
    id: EventGridManagementClientConfiguration
    path: azure-mgmt-eventgrid\azure\mgmt\eventgrid\event_grid_management_client.py
    remote:
      branch: master
      path: azure-mgmt-eventgrid\azure\mgmt\eventgrid\event_grid_management_client.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 23
  summary: 'Configuration for EventGridManagementClient

    Note that all parameters used to create this instance are saved as instance

    attributes.

    '
  syntax:
    content: EventGridManagementClientConfiguration(credentials, subscription_id,
      base_url=None)
    parameters:
    - description: 'Credentials needed for the client to connect to Azure.

        '
      id: credentials
      type:
      - msrestazure.azure_active_directory
    - description: 'Subscription credentials that uniquely identify a

        Microsoft Azure subscription. The subscription ID forms part of the URI

        for every service call.

        '
      id: subscription_id
      type:
      - str
    - description: 'Service URL

        '
      id: base_url
      type:
      - str
  type: class
  uid: azure.mgmt.eventgrid.event_grid_management_client.EventGridManagementClientConfiguration
references: []
